//  Auth0 & Web3Auth

const AUTH0_DOMAIN = 'https://dev-6432c6f6.us.auth0.com';

const SMS_CLIENT_ID_WEB3AUTH =
  'BAjBSILGC-_d0kJHW0wXuCKjrMQAe9goyyLT9EwsPmEfQSvZTKSE7oaciYwkGAzXttAiGusg2-Ajoyy0gfjWR1I';
const SMS_CLIENT_ID_AUTH0 = 'OOLi6dj6oA0B3zuPEQTCIhGLr5zP8r70';
const SMS_VERIFIER_WEB3AUTH = 'sms-auth0-verifier';

const TIKTOK_TEST_CLIENT_ID_WEB3AUTH =
  'BM1KCx4WNxmhKZ6pUY_SnOZLGZ3w_ZfcaSmQA_jbBCZnXcPE1qqsypeQJ3NVQ8Zu501QysPnMaoQEgM3Jx2YIls';
const TIKTOK_TEST_CLIENT_ID_AUTH0 =
  'VyWOy4DllS9qFtjDB2iI3gjCLfNfoVaf';
const TIKTOK_TEST_VERIFIER_WEB3AUTH = 'tiktok-auth0-verifier';

export {
  AUTH0_DOMAIN,
  SMS_CLIENT_ID_WEB3AUTH,
  SMS_CLIENT_ID_AUTH0,
  SMS_VERIFIER_WEB3AUTH,
  TIKTOK_TEST_CLIENT_ID_WEB3AUTH,
  TIKTOK_TEST_CLIENT_ID_AUTH0,
  TIKTOK_TEST_VERIFIER_WEB3AUTH,
};
